### ISSUE TITLE
Request: Add usage example with JSDoc

### ISSUE THREAD

**Issue by Radiergummi** [vue-styleguidist/vue-docgen-api#10]
This project seems to be exactly what I'm looking for, but I'm unsure on how to include it in my JSDoc workflow. Could you provide a general setup guide to make ends meet?  
Do I just have to include it as a plugin, like, create my `project.js` that holds several `vda.parse(x)` and return the result? Do I need to put more effort in?  

It would be nice to have some examples on how to set it up. Thank you!

**Comment by rafaesc** [comment]
Hi @Radiergummi,

there are some examples here: 
https://github.com/vue-styleguidist/vue-docgen-api/blob/master/tests/parse.js#L11

You can clone the repository and run the task `npm test`

Regards
