### ISSUE TITLE
v2.7.0 not published to npm

### ISSUE THREAD

**Issue by appinteractive** [vue-styleguidist/vue-docgen-api#103]
v2.7.0 is missing on npm!

**Comment by elevatebart** [comment]
Hello @appinteractive, 2.7.0 was a hickup in sematic release delivery. It was actually 3.0.0 with (very few) breaking changes. 

Why do you need it ?

**Comment by appinteractive** [comment]
The 3.0 is braking stuff in the package I use so I wanted to update to the latest working version and just saw that the 2.7 is missing. Thanks for the info.

**Comment by elevatebart** [comment]
That is unfortunate indeed. 
I made a real effort trying not to break anything when updating the API. 
Can you tell me what package is broken with 3.0?

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart
