### ISSUE TITLE
Use require extensions instead of vm.runInContext

### ISSUE THREAD

**Issue by znck** [vue-styleguidist/vue-docgen-api#11]
Parser does not work with external prop validation library (e.g. [prop-types](https://github.com/znck/prop-types)), mixin generator pattern (a function returning mixin) and external props.

You should instead use https://github.com/jackmellis/require-extension-hooks-vue to `require` vue components.

> P.S. Nice work guys. Loved vue-styleguidist.

**Comment by elevatebart** [comment]
Hello @znck  ! Can you please install 3.1.0 or vue-styleguidist 3 and tell me if you still have the issue ?

**Comment by elevatebart** [comment]
closing, as we do not intend to go down that route.
