### ISSUE TITLE
Is there a way to specify an alternate displayName? 

### ISSUE THREAD

**Issue by rinobatin** [vue-styleguidist/vue-docgen-api#121]
In my situation, my components have prefix. Having a way to specify another display name would be nice.

```js
export default {
 name: "myTextbox",
 displayName: "Textbox"
}
```

**Comment by elevatebart** [comment]
It is a great suggestion.
I will try my best to add it. 
To be honest I thought we already did.

**Comment by elevatebart** [comment]
I believe starting from 3.8 you can use ‘@displayName’ to customize the name of your component.
