### ISSUE TITLE
String value for `props[name].required`

### ISSUE THREAD

**Issue by sean-fixedpointcode** [vue-styleguidist/vue-docgen-api#122]
What does a string value for `required` indicate? Occasionally the `Documentation` result contains `required` properties with a `''` (empty string) value, including the example in `README.md`, but it's not clear why this value is being output.

**Comment by elevatebart** [comment]
Hello @sean-fixedpointcode you are absolutely right, this is weird. 
I kept it through the rewrite for backward compatibility. Maybe we could have a mode where it is done better ;)

**Comment by elevatebart** [comment]
@sean-fixedpointcode did I answer your question?
