### ISSUE TITLE
Add support pug slot

### ISSUE THREAD

**Issue by rafaesc** [vue-styleguidist/vue-docgen-api#13]
I copy this issue in this section because it refers on doc parser

https://github.com/vue-styleguidist/vue-styleguidist/issues/45#issuecomment-346222131

**Comment by blogui91** [comment]
Hey, any update about this issue?
Thanks!

**Comment by rafaesc** [comment]
Hi @blogui91,

At this moment, I will work in [ts-support](https://github.com/vue-styleguidist/vue-docgen-api/tree/ts-support).

However you can create a PR, It is necessary to create a pug parser here.
https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getSlots.js

First need to convert from pug to html, after that should continue the flow, to extract the slots.

You can tell me if you need help.

Regards

**Comment by simonwjackson** [comment]
Another vote for this to get implemented.
![carbon](https://user-images.githubusercontent.com/189379/38040520-4f6f6752-3275-11e8-9e9e-7ed3ac775754.png)

**Comment by rafaesc** [comment]
Fixed on 2.4.2 version!

Thanks to @mqqza
