### ISSUE TITLE
Doc generation of mixin props

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-docgen-api#2]
I have a mixin that adds props to the component. Is it possible for those props to also be documented with the component they are added to?

**Comment by rafaesc92** [comment]
I did not think about it, it's a good contribution, I need to add it in the vue styleguidist configuration to add the list of objects that will be the mixins and add them as global. Thanks! @lancetharper

**Comment by lancetharper** [comment]
Te lo agradezco pe causa!
