### ISSUE TITLE
TypeError: _vuex.createNamespacedHelpers

### ISSUE THREAD

**Issue by jkins** [vue-styleguidist/vue-docgen-api#24]
Any .vue using Vuex with:
```js
import { createNamespacedHelpers } from 'vuex'
const { mapState } = createNamespacedHeplers('name/space')
```

Outputs this when running vue-styleguidist:
```
Cannot parse src/Component.vue: TypeError: (0 , _vuex.createNamespacedHelpers) is not a function
```

Using:
* vue-docgen-api v2.3.1
* vue-styleguidist v1.4.8
* vuex v3.0.1

**Comment by rafaesc** [comment]
Hi @jkins,

update vue-docgen-api on last version, because it was fixed.

Regards!
