### ISSUE TITLE
"Dependencies not found"

### ISSUE THREAD

**Issue by KnaanBraz** [vue-styleguidist/vue-docgen-api#26]
```
These dependencies were not found:

* fs in ./~/vue-docgen-api/dist/parse.js, ./~/vue-docgen-api/dist/utils/getComponentModuleJSCode.js and 15 others
* child_process in ./~/jsdoc-api/lib/explain-sync.js, ./~/jsdoc-api/lib/explain.js and 1 other
* module in ./~/babel-core/lib/helpers/resolve.js
* net in ./~/debug/src/node.js
```

**Comment by rafaesc** [comment]
Hi @KnaanBraz,

I couldn't replicate this issue, you can try to remove node_modules folder and reinstall dependencies
Or you can send the step by step to replicate it.

Regards!

**Comment by adi518** [comment]
All we did is install it and then:
```js
import vueDocs from 'vue-docgen-api'
```
The error implies Node's `fs` wasn't bundled.

**Comment by rafaesc** [comment]
Hi @adi518,

but you import it to use in client side, for example through webpack or gulp?

**Comment by adi518** [comment]
Yes, via Webpack. I now tried it on a new `npm init` boilerplate and it works as expected. Should I exclude it from `babel-loader` in Webpack?

**Comment by adi518** [comment]
Ok, I think I got it now. I consumed it incorrectly. It's an infra package. So, it seems I only have to create a script where it runs through my `.vue` files and parse them into meta-data, then store that module and consume it regularly in my app.

**Comment by rafaesc** [comment]
Yes, in essence, it was developed to extract documentation of a vue application maybe how a devDependency. I hope it helps you

**Comment by adi518** [comment]
It should live in the devDependencies block, yes. Now I just have to think on a workflow that regularly updates the meta-data extracted from the components. If it works rather fast, I can do it with watch.
