### ISSUE TITLE
Inconsistent nulltype for descriptions

### ISSUE THREAD

**Issue by robcresswell** [vue-styleguidist/vue-docgen-api#28]
Empty `description` values have varying types; it would be helpful if they could be the same, just to make things easier when processing the results.

For example, a `prop` without a description will still contain `description: ""`, while a `slot` without a description will contain `description: null`. Personally I would vote for `description: ""`, as adding a key only to set it to `null` seems a bit redundant in my mind 😇

**Comment by rafaesc** [comment]
Hi @robcresswell,

yes, you are right, but at the same time I need change this in vue-styleguidist to work fine

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/rsg-components/Usage/Usage.js#L11

**Comment by robcresswell** [comment]
That shouldn't make too much of a difference; `!!null` and `!!""` shoud both be `false` :)

**Comment by rafaesc** [comment]
haha, it's true, so I will fix it.

**Comment by rafaesc** [comment]
Fixed it on 2.3.6
