### ISSUE TITLE
Populate events without comments

### ISSUE THREAD

**Issue by robcresswell** [vue-styleguidist/vue-docgen-api#29]
Is it possible to populate the events based off the presence of `$emit`? It would be nice to be able to populate the parser output with events automatically if `this.$emit` is called with a String as the first parameter, rather than expecting explicit documentation, much in the same as props and slots work.

**Comment by robcresswell** [comment]
Yeah I understand that it currently expects there to be documentation; it would be nice if it would at least populate the events even if there was no documentation. I'm currently using the API, but not the full style guide, to just generate simple README files for each of my components. This involves creating tables with props and their defaults, required, etc. and then a list of slots, and then a list of events. There may be a better way to do it, but this API was the one I had been using so far 👍

**Comment by rafaesc** [comment]
But you can do that if you create a script that extracts all `this.$emit` and save these events and then when it will be parsed by `vue-docgen-api` you could merge that object with your events saved.

I hope that you understood me, I still am working in my English :)

**Comment by robcresswell** [comment]
Yep, I understand; my motivation for opening this issue is if you would consider adding that as part of the API. Your English is excellent, btw.

**Comment by rafaesc** [comment]
Thanks, @robcresswell,

I think but this issue is something particular because only you want to extract all strings that match with  `this.$emit` without matters the documentation, maybe it is better that you manage it as a wrapper of vue-dogen-api.

**Comment by robcresswell** [comment]
Sure, will do.
