### ISSUE TITLE
Unexpected token import/export

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-docgen-api#3]
Since updating from 1.0.6 to 2.0.1 I get a SyntaxError for every component when I try to generate docs.

I get either `Unexpected token import` or `Unexpected token export`. Looks like es6 support got messed up?

**Comment by rafaesc92** [comment]
It should't, version 2 is generated through webpack from the server, if don't add the second, then default adds the babel-loader. I would have to check your repository.

However this type of parse is slow, I would not recommend implementing it with [Hot Module Replacement](https://webpack.js.org/api/hot-module-replacement/), these days I will add the parseLite that will be faster and integrate it into vue styleguidist.

**Comment by lancetharper** [comment]
Feel free to take a look. The only difference between these branches is this update.

`yarn install` then `yarn docs`

1.0.6: https://github.com/rei/rei-cedar/tree/future-vue

2.0.1: https://github.com/rei/rei-cedar/tree/test/docgen

**Comment by rafaesc92** [comment]
Done, it's already fixed, you need to update the vue-styleguidist. I was testing your project with Windows, and it compiled well. To document the mixins, you must add the [mixin tag](https://github.com/vue-styleguidist/vue-docgen-api#mixins). Unfortunately for now if you want to see the hot changes of the external mixins, you must restart the server.
