### ISSUE TITLE
A check should be added to verify the mixin is not already imported with ".js"

### ISSUE THREAD

**Issue by 0m4r** [vue-styleguidist/vue-docgen-api#32]
https://github.com/vue-styleguidist/vue-docgen-api/blob/ccdc2cc72ef9987291d05861e6840d40fbba642a/src/utils/getMixin.js#L9

if you import your mixin with something like:
```import Mixin from 'mixin.js'```
the line of code above 
```const pathRequire = filePath + '.js'```
fails to build the ```pathRequire``` as it generates it as 'mixins.js.js' instead of ```mixins.js```

**Comment by rafaesc** [comment]
Hi @0m4r,

Please send a PR, to merge it.

Regards!

**Comment by 0m4r** [comment]
@rafaesc I have a PR locally, that also solve the issue of adding the mixin props into a component that has not prop at all.... but I have not write permission so I cannot push my branch

**Comment by rafaesc** [comment]
@0m4r, perfect!, you can create a fork, then push all your commits in there and when it already ready you can create a PR in this project from your fork changes.

**Comment by 0m4r** [comment]
here you go: https://github.com/vue-styleguidist/vue-docgen-api/pull/37

**Comment by rafaesc** [comment]
It have been published on 2.3.10 version
