### ISSUE TITLE
lowercasing property types

### ISSUE THREAD

**Issue by robcresswell** [vue-styleguidist/vue-docgen-api#35]
In the Vue docs, property types are Constructors and thus, all uppercased. From what I can tell, the prop parsing code seems to forcibly lowercase all prop type names; is there any reason for this?

**Comment by rafaesc** [comment]
@robcresswell, yes, the main idea its to return similar an ouput like [react-docgen](https://github.com/reactjs/react-docgen)

Regards

**Comment by robcresswell** [comment]
Fair enough. I kind of think it is a shame to try and match React with a Vue documentation library, at the expense of not matching Vue's own documentation? But it is your library so it is your decision 👍
