### ISSUE TITLE
Can I use command line or use in jsdoc conf.json?

### ISSUE THREAD

**Issue by EdmundTheRadiance** [vue-styleguidist/vue-docgen-api#38]
Only program API?

**Comment by rafaesc** [comment]
@EdmundTheRadiance unfortunately, there isn't command line API.

Feel free to do it and send a PR. Regards

**Comment by elevatebart** [comment]
Since we are sunseting this repo and this request has a clone on vsg, I will close.
Please follow the referenced request.
