### ISSUE TITLE
Cannot parse Vuex mapGetters

### ISSUE THREAD

**Issue by sandeepk01** [vue-styleguidist/vue-docgen-api#4]
Components having the object spread operator syntax as well as mapGetters mixins used are not being parsed. Can it be handled or is there are configuration available to ignore it so that at least the parsing is complete?

Appreciate your help. Thanks.

**Comment by rafaesc92** [comment]
Sure, can you send me a source to review the case?
Have you tried with [parseWebpack](https://github.com/vue-styleguidist/vue-docgen-api#parsewebpackfilepath--webpackconfig-)?, is much more precise however a little slower.

I wait for your early reply. regards

**Comment by sandeepk01** [comment]
Added a source to mock the scenarios used, have shared my repo with you directly. Probably the parser is expecting the computed section to be typed as an Object.
Any thoughts to incorporate included Components in the docs?

**Comment by rafaesc92** [comment]
Fixed issue, please upgrade to version 1.1.6 of vue-styleguidist

**Comment by sandeepk01** [comment]
Thanks. Works like charm!
