### ISSUE TITLE
.babelrc not being picked up correctly?

### ISSUE THREAD

**Issue by davidhewitt** [vue-styleguidist/vue-docgen-api#40]
Hi,

I'm trying to document a file which uses the class properties syntax, and having problems. This is a reduced test case:

    <template>
      <div class="hello">
        Hello
      </div>
    </template>

    <script>
    class Foo {
      static foo = "bar";
    }

    export default {
      name: 'hello',
    };
    </script>

When I try to run `vue-styleguidist build`, I get the following error message (9:13 is referring to the `static foo = "bar";` line):

    SyntaxError: unknown: Unexpected token (9:13)

    Warning: Cannot parse src/components/Hello.vue: Error: SyntaxError: unknown: Unexpected token (9:13)

    It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
    https://github.com/vue-styleguidist/vue-docgen-api/issues

This is my .babelrc, which is working fine with webpack:

    {
      "presets": [
        ["env", {
          "modules": false,
          "targets": {
            "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
          }
        }],
        "stage-2"
      ],
      "plugins": ["transform-runtime", "transform-class-properties"]
    }

If I comment out all presets and plugins then webpack fails with the same SyntaxError, so I'm pretty sure my .babelrc is not being used by `vue-styleguidist`. Am I doing something wrong?

Thanks
David

**Comment by rafaesc** [comment]
@davidhewitt yes, you are right, vue-docgen-api has its babel config.

https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getParseBabel.js#L17

It would be awesome that you can send a PR to improve this feature.

**Comment by davidhewitt** [comment]
Sure, I might take a look this weekend.

**Comment by rafaesc** [comment]
Perfect!

**Comment by rafaesc** [comment]
Ready on version 2.3.13
