### ISSUE TITLE
Using file name instead of name prop

### ISSUE THREAD

**Issue by mwojtul** [vue-styleguidist/vue-docgen-api#42]
Adding a `name` property to components by default isn't necessary unless the component is a recursive component. Doing so has the chance to obfuscate the component file name in Vue devtools if it doesn't exactly match the given `name`, as that's what's used to generate the tag. For example: 

![screen shot 2018-07-20 at 5 20 34 pm](https://user-images.githubusercontent.com/1596316/43027656-47324bc4-8c41-11e8-9199-0e1b0ebd57f4.png)

Is it possible to tell `vue-docgen-api` to use the basename of the file instead? I tried using `propsParser` and setting the name, but it seems like that fires too late.

**Comment by elevatebart** [comment]
Hey!! I believe it works now. The only caveat is if the name of the file cannot be a valid html tag like text.vue or input.vue.

**Comment by mwojtul** [comment]
Awesome, thanks!
