### ISSUE TITLE
Error: JSDOC_ERROR: ERROR: Unexpected token import

### ISSUE THREAD

**Issue by michaelpumo** [vue-styleguidist/vue-docgen-api#44]
I am getting the following error when trying to do a dynamic import within my component (a Webpack feature?):

> JSDOC_ERROR: ERROR: Unable to parse /var/folders/cj/xqqjbxpj6ylbz5rs_89w8q2r0000gn/T/quxuq4lmsz8a5hd8zhg16b.js: Unexpected token import
> 
> Cannot parse src/elements/ImageMedia.vue: Error: JSDOC_ERROR: ERROR: Unable to parse /var/folders/cj/xqqjbxpj6ylbz5rs_89w8q2r0000gn/T/quxuq4lmsz8a5hd8zhg16b.js: Unexpected token import
> 
> It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
> https://github.com/vue-styleguidist/vue-docgen-api/issues

**Component script** (reduced for brevity)

```
<script>
const lazySizes = () => import("lazysizes") // This is the problem line.
</script>
```

I am actually building my components via Vue Design System (https://github.com/viljamis/vue-design-system) which I beieve used Vue Styleguidist under the hood. 

So, I'm not sure whether to report the problem there too.

Thanks.

**Comment by elevatebart** [comment]
Hello @michaelpumo ! Can you please install 3.1.0 or vue-styleguidist 3 and tell me if you still have the issue ?

**Comment by elevatebart** [comment]
Hello @michaelpumo, I believe this request was fixed by the last version of vue-docgen-api.

If you encounter it again, do not hesitate to open a new request. If you can, please include a reproduction repo.

Bart
