### ISSUE TITLE
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by rafaesc** [vue-styleguidist/vue-docgen-api#48]
Vue CLI version: 3.0.1
Reproduce step

* vue create my-project
* cd my-project
* vue add styleguidist
* yarn styleguide

`Error: can't find vue loader`

* yarn add vue-loader
* yarn styleguide

`It' work but : We couldn’t find any components using these patterns:`

* edit styleguide.config.js
* add: components: 'src/components/**/[A-Z]*.vue',

`Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspec t the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`

**Comment by DanielPe05** [comment]
Is there an update on this issue?

**Comment by rafaesc** [comment]
Fixed on version 2.5.0
