### ISSUE TITLE
TypeError: (0 , _library.libraryFunc) is not a function

### ISSUE THREAD

**Issue by AtofStryker** [vue-styleguidist/vue-docgen-api#53]
Hey all,

is there support for default functions?

example:

//@mypackage/packageA
export default function(){
  return {}
}

//@mypackage/packageB

import myFunc from '@mypackage/packageA'

//error happens here
myFunc()

Any idea why this is happening. It looks like vue-docgen-api is having issues parsing default functions? I can get a codepen together if there is a place I can drop vue-dcogen-api to reproduce. Please let me know if I can help or fix the issue.

**Comment by elevatebart** [comment]
Hello @AtofStryker ! Can you please install 3.1.0 or vue-styleguidist 3 and tell me if you still have th issue ?

**Comment by elevatebart** [comment]
I believe this issue is not relevant anymore, if you meet it agaoin please make sure all dependencies are up to date (especially docgen) and post a new issue.

Thank you for your support,
Bart
