### ISSUE TITLE
Is it possible to document computed functions too?

### ISSUE THREAD

**Issue by bengallienne** [vue-styleguidist/vue-docgen-api#56]
The title says it all really. We have our methods all nicely documented, but would like to add this documentation to our computeds as well, so people can understand what they do. Is this an option / on the roadmap?

Thanks!

**Comment by elevatebart** [comment]
It would mean evaluating the code before documenting code. 
That seems a hard task.

**Comment by bengallienne** [comment]
Just for my understanding please, why would you have to evaluate the code? The computeds are named functions under the computeds key, just like the methods are. I'm not disagreeing with you as I have no idea how it works, just asking to see if i can understand and maybe work out a useful alternative if this isn't possible.

**Comment by elevatebart** [comment]
Oooooooooh! my mistake! I understand now. You are talking about computed members.
I guess I was tired.

Do you use those computed members out of your component?
As you know we do not allow to document data for instance. 

I invite you to still document the computed properties in the JSDoc. hopefully vetur will help you pick it up and show it in context.

I do not see any use case yet for this feature.

**Comment by bengallienne** [comment]
@elevatebart ,

It does, thanks. However I'm not sure I agree. we tend to use computed properties as a means of creating filtered sets of things in our data, or to remove logic from the template itself. They are automatically watched which is useful, but sometimes it isn't immediately obvious what the computed member is doing without then finding the context within the template, so I find documenting them useful.

So I guess the two questions I would have for you are, why do you see that as dangerous to document? And also why do you mixins or watchers would be faster?

Thanks!

**Comment by elevatebart** [comment]
I do not debate the fact that computed properties should be documented. 
As internals (used only inside the current file) they are incredibly useful and can be hard to understand.
Documenting them is then absolutely crucial.

I do not think that a component should listen to computed properties of another.

Therefore documenting it as a published API would be my concern.

Would you share a component that would expose a computed property? Even simplified. This would help me understand your use case.

Thank you

**Comment by bengallienne** [comment]
Ok, so I think we are coming at this from slightly different directions, which is where the confusion may arise. 

I completely agree that a component should not listen to the computed properties of another, this is only for within a single file component. 

I think the key difference in what we are discussing, is that actually our use case is a large SaaS Single Page Application, and the documentation is for internal developer use only, not as a published API document. Its so new starters and existing devs can find out what everything does etc. I'll dig out an example later today unless this covers it?

Thanks!

**Comment by elevatebart** [comment]
Hello @bengallienne, I we agree 100% and I understand.
What you seem to look or is a place to document the computed properties of your components.
That make total sense and should be supported.

What vue-styleguidist does and by extension this library is a little different.
It creates a documentation on **how to use a component**. In this case, documenting computed properties would be useless since they are not supposed to be used outside of the component.

In order to document your computed properties, just add a JSDoc before the computed prop and use it when you have the componets code open. No need for it in the styleguide.

Hope what I am explaining makes sense, I do not think that we will implement this as of now.
I am trying to clean the bug pipe. 
If you find the use case you were talking about, please open a new issue.

**Comment by berdam** [comment]
> In order to document your computed properties, just add a JSDoc before the computed prop and use it when you have the componets code open. No need for it in the styleguide.

Hi @elevatebart it's a great library especially like that it parses docs from mixins! I'm using it to create custom .md files for my components but I'm also missing the computed properties. While I've read through the thread I still don't understand how could add docs for the computed properties. Can you show an example how to "just add a JSDoc before the computed prop"?

**Comment by bengallienne** [comment]
@elevatebart Thanks for the comments, I understand where you are coming from. We are adding the JSDoc blocks in the code for now, and advising developers to look at the code for information on computed properties. I do agree that this is something that should be supported for the use case of internally documenting an app built in Vue, but see why that is potentially not relevant here. Maybe in the future, some kind of configuration option to turn it on might be an option, but i'll leave that up to you :). Thanks again for your help.
