### ISSUE TITLE
vue-property-decorator types for @Props are all "unknown"

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-docgen-api#79]
When types are declared in vue-property-decorator syntax, they're not picked up properly by vue-docgen-api

```javascript
<script>
import { Vue, Component, Prop } from 'vue-property-decorator';
@Component
export default class MyComponent extends Vue {
    @Prop({ type: String }) text;

    /** Style properties to be overriden using $.css syntax */
    @Prop({ type: Object, default: () => ({}) }) styles;
}
</script>
```

<img width="171" alt="screen shot 2019-01-22 at 11 33 21 am" src="https://user-images.githubusercontent.com/2801156/51529801-c050ca00-1e39-11e9-9343-ff04d022c491.png">

**Comment by elevatebart** [comment]
Yess !!! Thank you again, I am on it

**Comment by elevatebart** [comment]
Sorry for being my Ginea Pig,,, :-$

**Comment by JessicaSachs** [comment]
Happy to help :-)

I like this tool very much. I'm seeing some performance issues though, and I'm wondering if I can get ahold of you to chat more realtime. Is there a discord channel, or can we join the Vue discord and perhaps discuss under a new #styleguidist channel? There's one for Storyboard.

**Comment by elevatebart** [comment]
I just created a channel here: https://discord.gg/MBY5Pu
