### ISSUE TITLE
vue-template-compiler version mismatch

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-docgen-api#8]
Updated to vue 2.4.2 recently and `vue-styleguidist` gives an error of a version mismatch between `vue` (2.4.2) and `vue-template-compiler` (2.4.1). 

I traced it back to the dependency here for `vue-template-compiler` at 2.3.4 

It works if I manually change it to 2.4.2 in my project's lock file.

**Comment by rafaesc92** [comment]
Ok, I've published the fix under v1.2.1 of vue-styleguidist.
