### ISSUE TITLE
Basic support for vue-styled-components

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-docgen-api#95]
Can we get support for vue-styled-components? It would be great to render the components in the documentation. Rendering props would be nice, but is not necessary.

Right now, an error is thrown in the console

```
⠸ Compiling...Warning: Cannot parse src/components/buttons/StyledButton.vue: Error: No suitable component definition found

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
https://github.com/vue-styleguidist/vue-docgen-api/issues
```

The component looks like this:

```javascript
<script>
import styled from 'vue-styled-components';
const StyledButton = styled('button')`
    padding: 0 10px;
    margin: 0;
    box-shadow: 1px 2px 3px rgba(0, 0, 0, .1);
    overflow: hidden;
`;

export default StyledButton;
</script>
```

**Comment by Acidic9** [comment]
Is there currently any way to use vue styleguidist with styled commponents?

**Comment by elevatebart** [comment]
Hey guys !! Since we have a workaround I will close this one.

Please have a looksie at the cookbook.
https://vue-styleguidist.github.io/Cookbook.html

Thank you @jessicasachs
