### ISSUE TITLE
Parse error: cannot resolve module

### ISSUE THREAD

**Issue by AldericWend** [vue-styleguidist/vue-docgen-api#98]
Using vue-styleguidist 3.0.9.

I get the following error in a SFC .vue file importing a mixin .js file:

`Warning: Cannot parse resources\assets\js\components\items\actions\ItemAction.vue: Error: Neither 'assets/js/components/mixins/classGenerator.vue' nor 'assets/js/components/mixins/classGenerator.js', not even 'assets/js/components/mixins/classGenerator/index.js' or 'assets/js/components/mixins/classGenerator/index.ts' could be found in 'W:\partners.dev.viaevista.fr\partners-fc\laravel\resources\assets\js\components\items\actions'`

Maybe it's because vue-docgen-api does not rely on webpack, right?
But for information, here is the import statement:

`import classGenerator from "assets/js/components/mixins/classGenerator";`

And here is a snippet of the webpack config for resolving modules:

`    resolve: {
        modules: [
            path.resolve(__dirname, 'resources'),
            'node_modules'
        ],`

Best regards.

AldericWend

**Comment by elevatebart** [comment]
You are absolutely right and I need to implement that. The issue is actually in vue-styleguidist, that does not seem to resolve all aliases of webpack (only alias for now). I could add the resolve.

If you cannot wait, you can always add an alias for your assets and fix it this way.
